<template><div><h1 id="about-vausly-media" tabindex="-1"><a class="header-anchor" href="#about-vausly-media"><span>About Vausly Media</span></a></h1>
<h2 id="intro" tabindex="-1"><a class="header-anchor" href="#intro"><span>Intro</span></a></h2>
<p>Hello, I am the admin of Vausly Media. Vausly ​is my digital identity. I really enjoy writing ​articles about anything I like such as the ​internet world, internet culture, computer ​technology, history, or anything related to that. ​I also write articles about tutorials and also ​information about games. Sometimes I also share ​my real-life stories or experiences that I think ​are meaningful or difficult to forget.</p>
<p>I also like to play games. The games I play ​are Minecraft, Clash of Clans, Mobile Legends: ​Bang Bang, etc. My favorite games are open world. That's why Minecraft is the game I like ​the most from all the games I play.</p>
<h2 id="my-projects" tabindex="-1"><a class="header-anchor" href="#my-projects"><span>My Projects</span></a></h2>
<p>I a lot of projects on the internet, including <a href="https://www.vausly.com" target="_blank" rel="noopener noreferrer">Vausly Post</a>, where I write articles about games, the internet, tutorials, and so on. I also have a channel on YouTube where I make videos. Actually there are so many projects that I do I can't explain.</p>
<h2 id="when-did-i-start-creating-digital-content" tabindex="-1"><a class="header-anchor" href="#when-did-i-start-creating-digital-content"><span>When did I start creating digital content?</span></a></h2>
<p>I created my first digital content in 2017. There was a service called UTK.io, Created by an internet user named Chris on 30th September 2014. It was a service where ​you could share your Minecraft ​creations with the world, such as ​Maps, Mods, Seeds, Textures, etc. ​It was like a content creation ​platform. I started to upload my first content on 11th November 2017 and was well received by the community. One of my posts was featured by its developer in 2018. I abandoned that project ​in mid-2019 because I was too busy. ​Until the service was fully closed ​on 1st January 2023 by the original creator. But I see the site changed ownership to another person in September 2024. The content is still about Minecraft, but not in the format of a content creation platform.</p>
<h2 id="when-did-you-start-make-a​-video-content" tabindex="-1"><a class="header-anchor" href="#when-did-you-start-make-a​-video-content"><span>When did you start make a​ video content?</span></a></h2>
<p>On 29th June 2017, I created a YouTube channel which is now called <a href="https://www.youtube.com/channel/UCabb5RfYa62j44O_uUPZI5A?sub_confirmation=1" target="_blank" rel="noopener noreferrer">VausProject</a>. At first I made it just for fun. But I remembered about my friend who had made a video on YouTube in 2016. This inspired me to have the interest to make a video on YouTube. I got my first subscriber on 31st December 2017 just for commenting on someone's video on YouTube, entitled “<a href="https://m.youtube.com/watch?v=HdzMobjXr4Q" target="_blank" rel="noopener noreferrer">Fenomena Langit di Tahun 2018 Menurut Kalender Astronomi 2018</a>”. And my first subscriber was <a href="https://www.youtube.com/channel/UCtcUaJ7-V23zJ4rckk1xpMA?sub_confirmation=1" target="_blank" rel="noopener noreferrer">Mr. R (also known as Mr Ridwan)</a>.</p>
<p>The year after that, on 11th October 2018, I created a new channel which is now my main channel, now called <a href="https://www.youtube.com/channel/UCC8XmP-H3_bUKavcudu_M9g?sub_confirmation=1" target="_blank" rel="noopener noreferrer">Vausly</a>. I first started creating video ​content on 31st December 2018 on ​YouTube on that channel.</p>
<h2 id="which-platforms-do-you-create-content-on" tabindex="-1"><a class="header-anchor" href="#which-platforms-do-you-create-content-on"><span>Which platforms do you create content on?</span></a></h2>
<p>I create content on many platforms, including YouTube, Instagram, TikTok, Facebook, and so on. You can check my social media here: <a href="https://bio.vausly.com/" target="_blank" rel="noopener noreferrer">https://bio.vausly.com/</a>.</p>
<h2 id="where-you-live-now" tabindex="-1"><a class="header-anchor" href="#where-you-live-now"><span>Where you live now?</span></a></h2>
<p>I live in Pontianak, West Kalimantan, Indonesia.</p>
<h2 id="my-hobby" tabindex="-1"><a class="header-anchor" href="#my-hobby"><span>My Hobby</span></a></h2>
<p>Reading.</p>
<h2 id="other-information" tabindex="-1"><a class="header-anchor" href="#other-information"><span>Other Information</span></a></h2>
<p>For shorter information, <a href="https://www.vausly.my.id" target="_blank" rel="noopener noreferrer">visit landing page</a></p>
</div></template>


