<template><div><h1 id="tentang-vausly-media" tabindex="-1"><a class="header-anchor" href="#tentang-vausly-media"><span>Tentang Vausly Media</span></a></h1>
<h2 id="intro" tabindex="-1"><a class="header-anchor" href="#intro"><span>Intro</span></a></h2>
<p>Saya adalah admin dari Vausly Media, saya sangat senang menulis artikel tentang hal yang saya sukai seperti seputar dunia internet, internet culture, teknologi komputer, history, atau yang berhubungan dengan itu. Saya juga menulis artikel mengenai tutorial dan juga informasi mengenai suatu game. Terkadang saya juga membagikan cerita tentang kisah nyata yang saya alami atau pengalaman saya yang menurut saya berkesan atau bisa dibilang sulit untuk dijauhkan.</p>
<p>Saya juga suka dengan game. Game yang saya mainkan di antaranya adalah Minecraft, Clash of Clans, Mobile Legends: Bang Bang, dll. Game favorit saya adalah game yang bersifat open world, itulah sebabnya Minecraft adalah game yang paling saya suka diantara game yang saya mainkan.</p>
<h2 id="my-projects" tabindex="-1"><a class="header-anchor" href="#my-projects"><span>My Projects</span></a></h2>
<p>Saya memiliki banyak proyek di internet, termasuk diantaranya Vausly Post, di mana saya menulis artikel tentang game, internet, tutorial, dan sebagainya. Saya juga memiliki channel di YouTube di mana saya membuat konten video. Sebenarnya ada begitu banyak proyek yang pernah saya kerjakan yang tidak bisa saya jelaskan satu per satu.</p>
<h2 id="kapan-saya-mulai-membuat-konten-digital" tabindex="-1"><a class="header-anchor" href="#kapan-saya-mulai-membuat-konten-digital"><span>Kapan saya mulai membuat konten digital?</span></a></h2>
<p>Saya membuat konten digital secara publik pada tahun 2017. Terdapat sebuah layanan bernama UTK.io, yang dibuat oleh seorang pengguna internet bernama Chris pada tanggal 30 September 2014. Itu adalah layanan di mana Anda dapat berbagi kreasi Minecraft Anda dengan dunia, seperti Peta, Mod, Seeds, Tekstur, dll. UTK.io itu seperti platform pembuatan konten (ccontent creation). Saya mulai mengupload konten pertama saya pada tanggal 11 November 2017 dan mendapatkan respon yang sangat baik oleh komunitas. Salah satu postingan saya pernah masuk dalam daftar unggulkan oleh pengembangnya pada tahun 2018. Saya meninggalkan proyek itu pada pertengahan 2019 dikarenakan saya terlalu sibuk. Hingga layanan ini ditutup sepenuhnya pada 1 Januari 2023 oleh pembuat aslinya. Namun saya melihat situs tersebut berpindah kepemilikan ke orang lain pada September 2024. Kontennya masih tentang Minecraft, tetapi tidak dalam format platform pembuatan konten.</p>
<h2 id="kapan-saya-mulai-membuat-konten-video" tabindex="-1"><a class="header-anchor" href="#kapan-saya-mulai-membuat-konten-video"><span>Kapan saya mulai membuat konten video?</span></a></h2>
<p>Pada tanggal 29 Juni 2017, saya membuat sebuah channel YouTube yang sekarang namanya adalah <a href="https://www.youtube.com/channel/UCabb5RfYa62j44O_uUPZI5A?sub_confirmation=1" target="_blank" rel="noopener noreferrer">VausProject</a>. Awalnya saya membuatnya hanya untuk iseng. Namun saya pernah teringat mengenai teman saya yang pernah membuat video di YouTube pada tahun 2016. Hal tersebut menginspirasi saya memiliki keinginan untuk membuat video di YouTube. Hingga akun tersebut mendapatkan pelanggan pertamanya pada 31 Desember 2017 hanya karena berkomentar di sebuah video seseorang di YouTube, yang berjudul &quot;<a href="https://m.youtube.com/watch?v=HdzMobjXr4Q" target="_blank" rel="noopener noreferrer">Fenomena Langit di Tahun 2018 Menurut Kalender Astronomi 2018</a>&quot;. Dan subscriber pertama saya adalah <a href="https://www.youtube.com/channel/UCtcUaJ7-V23zJ4rckk1xpMA?sub_confirmation=1" target="_blank" rel="noopener noreferrer">Mr. R (atau dikenal sebagai Mr Ridwan)</a>.</p>
<p>Setahun setelahnya, pada tanggal 11 Oktober 2018, saya membuat channel baru yang sekarang menjadi channel utama saya, yang sekarang bernama <a href="https://www.youtube.com/channel/UCC8XmP-H3_bUKavcudu_M9g?sub_confirmation=1" target="_blank" rel="noopener noreferrer">Vausly</a>. Saya pertama kali mulai membuat konten video pada tanggal 31 Desember 2018 di YouTube, di channel tersebut.</p>
<h2 id="di-platform-apa-saja-anda-membuat-konten" tabindex="-1"><a class="header-anchor" href="#di-platform-apa-saja-anda-membuat-konten"><span>Di platform apa saja Anda membuat konten?</span></a></h2>
<p>Saya membuat konten di banyak platform, termasuk YouTube, Instagram, TikTok, Facebook, dan sebagainya. Anda dapat memeriksa media sosial saya di sini:<a href="https://bio.vausly.com/" target="_blank" rel="noopener noreferrer">https://bio.vausly.com/</a>.</p>
<h2 id="tinggal-di-mana" tabindex="-1"><a class="header-anchor" href="#tinggal-di-mana"><span>Tinggal di mana?</span></a></h2>
<p>Saya tinggal di Pontianak, Kalimantan Barat, Indonesia.</p>
<h2 id="hobi-saya" tabindex="-1"><a class="header-anchor" href="#hobi-saya"><span>Hobi saya</span></a></h2>
<p>Membaca.</p>
<h2 id="other-information" tabindex="-1"><a class="header-anchor" href="#other-information"><span>Other Information</span></a></h2>
<p>Untuk info singkat, <a href="https://www.vausly.my.id" target="_blank" rel="noopener noreferrer">kunjungi landing page</a></p>
</div></template>


